using System;
using System.Reflection;
using System.Reflection.Emit;
using Wissance.WebApiToolkit.Core.Data;
using Wissance.WebApiToolkit.Data.Entity;
using Wissance.WebApiToolkit.Ef.Controllers;

namespace Wissance.WebApiToolkit.Ef.Generators
{
    internal static class OnTheFlyServicesGenerator
    {
        public static Tuple<Assembly, string> GenerateController<TObj, TId, TFilter>(string assemblyName, string controllerName, 
            bool saveOnDisk,  TObj entity, TId entityId, ControllerType controllerType, TFilter filter)
            where TObj: class, IModelIdentifiable<TId>
            where TId: IComparable
            where TFilter: class, IReadFilterable
        {
            try
            {
                AssemblyName name = new AssemblyName(assemblyName);
                AssemblyBuilderAccess access = saveOnDisk ? AssemblyBuilderAccess.RunAndCollect : AssemblyBuilderAccess.Run;
                AssemblyBuilder assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(name, access);
                
                string fullControllerName = $"{controllerName}Controller";
                ModuleBuilder moduleBuilder = assemblyBuilder.DefineDynamicModule($"AutoGenerated{fullControllerName}");
                Type basicControllerType = GetAppropriateBaseControllerType<TObj, TId, TFilter>(controllerType);
                TypeBuilder typeBuilder = moduleBuilder.DefineType(fullControllerName,
                    TypeAttributes.Public | TypeAttributes.Class, basicControllerType);
                return null;
            }
            catch (Exception e)
            {
                return new Tuple<Assembly, string>(null, e.Message);
            }
        }
        
        private static Type GetAppropriateBaseControllerType<TObj, TId, TFilter>(ControllerType controllerType)
            where TObj: class, IModelIdentifiable<TId>
            where TId: IComparable
            where TFilter: class, IReadFilterable
        {
            switch (controllerType)
            {
                case ControllerType.ReadOnly:
                    return typeof(GenericReadOnlyController<TObj, TObj, TId, TFilter>);
                case ControllerType.FullCrud:
                    return typeof(GenericCrudController<TObj, TObj, TId, TFilter>);
                case ControllerType.Bulk:
                    return typeof(GenericCrudController<TObj, TObj, TId, TFilter>);
                default:
                    return typeof(GenericCrudController<TObj, TObj, TId, TFilter>);
            }
        }
    }
}